CREATE DATABASE PRIMARK_SHOP;
USE PRIMARK_SHOP;
-- drop database PRIMARK_SHOP;

CREATE TABLE CATEGORIAS
(
  IdCategoria INT NOT NULL,
  Categorias VARCHAR(35) NOT NULL,
  PRIMARY KEY (IdCategoria)
);



INSERT INTO CATEGORIAS VALUES (1,'DAMAS');
INSERT INTO CATEGORIAS VALUES (2,'CABALLEROS');
INSERT INTO CATEGORIAS VALUES (3,'INFANTIL');
