CREATE DATABASE PRIMARK_SHOP;
USE PRIMARK_SHOP;
-- drop database PRIMARK_SHOP;

CREATE TABLE LOGIN
(
  IdLogin INTEGER NOT NULL,
  Contrasegna VARCHAR(25) NOT NULL,
  Usuario VARCHAR(35) NOT NULL,
  TipoEmpleado SMALLINT NOT NULL,
  IdEmpleado INTEGER NOT NULL,
  PRIMARY KEY (IdLogin),
  FOREIGN KEY (IdEmpleado) REFERENCES EMPLEADOS(IdEmpleado)
);
-- 1 Empleado comun
-- 2 Admin
-- 3 Encargado
INSERT INTO LOGIN VALUES (1, 'ENRTORGZZ01', 'ENRIQUE TORRES GONZALEZ', 1, 1);
INSERT INTO LOGIN VALUES (2, 'JOSPERSAL02', 'JOSE ALFREDO PEREZ SALAZAR', 1, 2);
INSERT INTO LOGIN VALUES (3, 'DIATREGON03', 'DIANA LAURA TREJO GONZALEZ', 2, 3);
INSERT INTO LOGIN VALUES (4, 'SUSAGUFLO04', 'SUSANA AGUILAR FLORES', 2, 4);
INSERT INTO LOGIN VALUES (5, 'JAISOTCAR05', 'JAIME SOTELO CARDENAS', 2, 5);
INSERT INTO LOGIN VALUES (6, 'JOHDURMOR06', 'JOHANNA DURAN MORENO', 2, 6);
INSERT INTO LOGIN VALUES (7, 'KARESTMAR07', 'KAREN ESTRADA MARTINEZ', 3, 7);
INSERT INTO LOGIN VALUES (8, 'ALFFERROS08', 'ALFREDO FERNANDEZ ROSAS', 3, 8);
INSERT INTO LOGIN VALUES (9, 'JESUSCRACK1', 'JESUS PEREZ CERVANTES', 3, 9);
INSERT INTO LOGIN VALUES (10, 'SAMUELLL10', 'SAMUEL HERNANDEZ FERNANDEZ', 3, 10);
DELETE FROM LOGIN WHERE IdLogin = 1;
select * from login;