CREATE DATABASE PRIMARK_SHOP;
USE PRIMARK_SHOP;
-- drop database PRIMARK_SHOP;

CREATE TABLE PRODUCTOS
(
  IdProducto INTEGER NOT NULL,
  NombreProducto VARCHAR(35) NOT NULL,
  Descripcion VARCHAR(150) NOT NULL,
  CostoProducto DECIMAL NOT NULL,
  PrecioProducto DECIMAL NOT NULL,
  Proveedor VARCHAR(35) NOT NULL,
  IdCategoria INTEGER NOT NULL,
  PRIMARY KEY (IdProducto),
  FOREIGN KEY (IdCategoria) REFERENCES CATEGORIAS(IdCategoria)
);


INSERT INTO PRODUCTOS VALUES (1, 'BLUSA', 'POLO BLANCA CHICA', 120, 300, 'PRENDAS GEORGE', 1);
INSERT INTO PRODUCTOS VALUES (2, 'CAMISA', 'VESTIR NEGRA HOMBRE MEDIANO', 150, 400, 'MARISCAL', 2);
INSERT INTO PRODUCTOS VALUES (3, 'PANTALON', 'MEZCLILLA AZUL MUJER CHICO', 300, 650, 'LEVIS', 1);
INSERT INTO PRODUCTOS VALUES (4, 'PLAYERA', 'BLANCA HOMBRE GRANDE', 120, 260, 'HANES', 2);
INSERT INTO PRODUCTOS VALUES (5, 'PLAYERA', 'BLANCA HOMBRE GRANDE', 120, 260, 'HANES', 2);
INSERT INTO PRODUCTOS VALUES (6, 'VESTIDO', 'ROSA MUJER MEDIANO', 200, 500,'ZARA', 1);
INSERT INTO PRODUCTOS VALUES (7, 'PLAYERA', 'VERDE NINO CHICA', 150, 320,'PRENDAS GEORGE', 3);
INSERT INTO PRODUCTOS VALUES (9, 'FALDA', 'NEGRA MUJER GRANDE', 165, 400, 'ZARA', 1);
INSERT INTO PRODUCTOS VALUES (10, 'VESTIDO', 'VERDE NINA CHICO', 150, 350, 'ZARA', 3);
-- Agrege descripcion
-- Elimine estado