CREATE TABLE VENTA_DETALLE
(
  IdVentaDetalle INTEGER NOT NULL,
  Cantidad INTEGER NOT NULL,
  IdProducto INTEGER NOT NULL,
  IdVenta INTEGER NOT NULL,
  PRIMARY KEY (idVentaDetalle),
  FOREIGN KEY (IdProducto) REFERENCES PRODUCTOS(IdProducto),
  FOREIGN KEY (IdVenta) REFERENCES VENTAS(IdVenta)
);


INSERT INTO VENTA_DETALLE VALUES (1, 30, 1, 1);
INSERT INTO VENTA_DETALLE VALUES (2, 65, 7, 1);
INSERT INTO VENTA_DETALLE VALUES (3, 32, 7, 1);
INSERT INTO VENTA_DETALLE VALUES (4, 35, 10,1);
INSERT INTO VENTA_DETALLE VALUES (5, 40, 9, 2);
INSERT INTO VENTA_DETALLE VALUES (6, 30, 6, 2);
INSERT INTO VENTA_DETALLE VALUES (7, 50, 5, 3);
INSERT INTO VENTA_DETALLE VALUES (8, 32, 2, 3);
INSERT INTO VENTA_DETALLE VALUES (9, 31, 3, 3);
INSERT INTO VENTA_DETALLE VALUES (10, 23, 4,4);